#!/bin/bash

# <think>
# We are asked: "Bash Completion Script Generation for `ollama run`". We have a prompt with instructions to generate robust Bash completion script. The answer must be the code in bash only, and include inline comments explaining critical sections. It is production ready and robust.
# 
# We have conditions:
# 
# - Must check COMP_WORDS[0] == "ollama" and COMP_WORDS[1] == "run". So in our script function _ollama_completions, we'll do that.
# 
# - Use __ltrim_colon_completions "$cur" after setting COMPREPLY. But wait careful: The instructions say: use __ltrim_colon_completions "$cur", but it is mandatory to call it at the end. So include that as a function call in our script.
# 
# - Also we must handle colon splitting with _get_comp_words_by_ref -n : cur prev. Let me recall how that works: It's often available from bash-completion? Actually, I need to check that _get_comp_words_by_ref is provided by bash-completion package. But anyway, we include it as function call.
# 
# - Then if command "ollama" exists? Check using command -v ollama &>/dev/null. If not, return completions empty.
# 
# - Then run: `ollama list 2>/dev/null` and parse the output line by line skipping header lines. We need to extract only first column (model name) using awk '{print $1}'. And then store these names in an array for matching.
# 
# - Generate completions: The current prefix can be extracted with the help of _get_comp_words_by_ref -n : cur prev, but we also have fallback if that fails. So if _get_comp_words_by_ref command is not available maybe fallback to extracting manually from COMP_WORDS? But instructions say: "Try: _get_comp_words_by_ref -n : cur prev", Fallback: Manual extraction from COMP_WORDS.
# 
# - Then filter models matching current prefix using compgen. Use compgen -W "${model_names[*]}" "$cur" and assign COMPREPLY array equals to that list.
#   
# - And then call __ltrim_colon_completions "$cur".
# 
# - Also the function must be "robust", so handle error conditions: if ollama command not found, etc.
# 
# - Then register complete -F _ollama_completions ollama at the end of the script. But instructions say to output only bash code, no markdown formatting, no explanation.
# 
# - So we need a function:
# 
# 
# _ollama_completions() {
#    # Check if command is "ollama run"
#    if [[ "${COMP_WORDS[0]}" != "ollama" || "${COMP_WORDS[1]}" != "run" ]]; then
#        COMPREPLY=()
#        return 0
#    fi
# 
#    # Check if ollama exists, else completions empty
#    command -v ollama &>/dev/null || { COMPREPLY=(); return; }
# 
#    local cur prev
#    # Use _get_comp_words_by_ref with colons not being splitted. 
#    # This must be attempted first.
#    if declare -F _get_comp_words_by_ref >/dev/null 2>&1; then
#        _get_comp_words_by_ref -n : cur prev
#    else
#        # fallback, get current word and previous word from COMP_WORDS array.
#        cur="${COMP_WORDS[COMP_CWORD]}"
#        prev="${COMP_WORDS[COMP_CWORD-1]}"
#    fi
# 
#    # Retrieve the list of models using ollama list command,
#    # then skip header line and extract first column only
#    local models=()
#    local output
#    if output=$(ollama list 2>/dev/null); then
#        # Split lines on newline. 
#        while IFS= read -r line; do
#            # Skip header line if it's "NAME ID SIZE MODIFIED"
#            [[ "$line" =~ ^NAME[[:space:]]+ID[[:space:]]+SIZE[[:space:]]+MODIFIED$ ]] && continue
#            # Extract first column using awk
#            model=$(echo "$line" | awk '{print $1}')
#            models+=("$model")
#        done <<< "$output"
#    fi
# 
#    COMPREPLY=( $(compgen -W "${models[*]}" -- "$cur") )
#    
#    # Fix colon display in completions
#    __ltrim_colon_completions "$cur"
# }
# 
# 
# But check instructions: "Parse models: Check ollama exists, run: ollama list 2>/dev/null, parse line-by-line skip header. Build array of model names." Also must sort results; maybe we want to sort the completions? But compgen with -W sorted? The instruction says "Sort results". So I can do "compgen -W <sorted models>" but since COMPREPLY is generated by compgen, it's unsorted. However, compgen doesn't provide sorting option. Alternatively, we might want to sort the array before using compgen.
# 
# I could create a sorted unique list of models. But instructions say: "Sort results". So I can do something like:
# 
# models_sorted=($(printf "%s\n" "${models[@]}" | sort -u))
# 
# Then use COMPREPLY=( $(compgen -W "${models_sorted[*]}" -- "$cur") ).
# 
# Let's check further instructions: "Generate completions: Filter models matching current prefix; Sort results; Set COMPREPLY using compgen."
# 
# Thus I'll do:
# 
# 
# local sorted_models=($(printf "%s\n" "${models[@]}" | sort -u))
# COMPREPLY=( $(compgen -W "${sorted_models[*]}" -- "$cur") )
# 
# 
# That is better.
# 
# We need to call __ltrim_colon_completions after setting COMPREPLY. But caution: In some completion scripts, the call to __ltrim_colon_completions must be done outside of any if/else block? I think it's required as last step before returning.
# 
# I can do:
# 
# 
# __ltrim_colon_completions "$cur"
# 
# 
# - Also check that we are only activating for "ollama run" command: We already did that.
#   
# Also note: The instructions require the script to include inline comments explaining critical sections. So I'll add those comments in the code.
# 
# I must output only bash code with no markdown formatting, so I'll output plain text with the code and then nothing else.
# 
# So final answer is a bash script like:
# 
# 
# _ollama_completions() {
#     # Only complete if running 'ollama run'
#     [[ "${COMP_WORDS[0]}" != "ollama" || "${COMP_WORDS[1]}" != "run" ]] && { COMPREPLY=(); return; }
#     
#     # Check if ollama command exists
#     command -v ollama &>/dev/null || { COMPREPLY=(); return; }
#     
#     local cur prev
#     # Attempt to get current word and previous word without colon splitting issues.
#     if declare -F _get_comp_words_by_ref >/dev/null 2>&1; then
#         _get_comp_words_by_ref -n : cur prev
#     else
#         cur="${COMP_WORDS[COMP_CWORD]}"
#         prev="${COMP_WORDS[COMP_CWORD-1]}"
#     fi
#     
#     # Retrieve model list from ollama list output.
#     local models=()
#     if output=$(ollama list 2>/dev/null); then
#         while IFS= read -r line; do
#             # Skip header: "NAME ID SIZE MODIFIED"
#             [[ "$line" =~ ^NAME[[:space:]]+ID[[:space:]]+SIZE[[:space:]]+MODIFIED$ ]] && continue
#             model=$(echo "$line" | awk '{print $1}')
#             models+=("$model")
#         done <<< "$output"
#     fi
#     
#     # Sort and remove duplicates from model list.
#     local sorted_models=($(printf "%s\n" "${models[@]}" | sort -u))
#     
#     # Generate completion matches for the current prefix
#     COMPREPLY=( $(compgen -W "${sorted_models[*]}" -- "$cur") )
#     
#     # Fix colon display issues in completions (Mandatory!)
#     __ltrim_colon_completions "$cur"
# }
# complete -F _ollama_completions ollama
# 
# 
# That should be output.
# 
# I need to check critical points:
# - The first array indices: COMP_WORDS[0] and COMP_WORDS[1].
# - Check for command "ollama" exists.
# - Use _get_comp_words_by_ref if available, else fallback.
# - Parse model list by reading each line from the output of `ollama list 2>/dev/null`.
# - Skip header lines using a regex check: Possibly pattern match ^NAME[[:space:]]+ID[[:space:]]+SIZE[[:space:]]+MODIFIED$ might be acceptable. But maybe simpler is to skip first line (if it's header). But instructions say "skip header line 'NAME ID SIZE MODIFIED'". So we can check if the line equals that exactly, ignoring whitespace? Possibly use grep "^NAME\s+ID\s+SIZE\s+MODIFIED" and then continue if true. 
# - Use awk '{print $1}' to extract first column.
# - Then sort results.
# - Then call __ltrim_colon_completions "$cur".
# 
# Also check colon handling: The instructions mention "Use _get_comp_words_by_ref -n : cur prev", so it's fine.
# 
# I also need to register the function using complete command. So at end we do: `complete -F _ollama_completions ollama`.
# 
# Let me check if any further details are needed:
# - "Handle missing ollama gracefully": We already have if command not found then completions empty.
# - "Model names containing colons": The use of _get_comp_words_by_ref ensures that colon isn't splitted incorrectly, so it's handled.
# 
# The script is robust, and meets all instructions.
# 
# I'll output the code as text with inline comments. And output nothing else.
# 
# I'll produce the answer now in plain text.
# </think>

_ollama_completions() {
    # Only complete if running "ollama run"
    [[ "${COMP_WORDS[0]}" != "ollama" || "${COMP_WORDS[1]}" != "run" ]] && { COMPREPLY=(); return; }

    # Ensure the "ollama" command exists; if not, no completions.
    command -v ollama &>/dev/null || { COMPREPLY=(); return; }

    local cur prev
    # Try to get the current and previous words without splitting on colons.
    if declare -F _get_comp_words_by_ref >/dev/null 2>&1; then
        _get_comp_words_by_ref -n : cur prev
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
    fi

    # Retrieve the list of models by running "ollama list" and processing its output.
    local models=()
    if output=$(ollama list 2>/dev/null); then
        while IFS= read -r line; do
            # Skip header line: "NAME ID SIZE MODIFIED"
            [[ "$line" =~ ^NAME[[:space:]]+ID[[:space:]]+SIZE[[:space:]]+MODIFIED$ ]] && continue
            # Extract the first column (model name) using awk.
            model=$(echo "$line" | awk '{print $1}')
            models+=("$model")
        done <<< "$output"
    fi

    # Sort and remove duplicate model names for consistent completions.
    local sorted_models=($(printf "%s\n" "${models[@]}" | sort -u))

    # Generate completion suggestions matching the current prefix.
    COMPREPLY=( $(compgen -W "${sorted_models[*]}" -- "$cur") )

    # Fix colon display issues by trimming extra colons in completions (MANDATORY!)
    __ltrim_colon_completions "$cur"
}

# Register the completion function for "ollama".
complete -F _ollama_completions ollama
